### ISSUE TITLE
Support for ARM/M1

### ISSUE THREAD

**Issue by neilconway** [guard/rb-fsevent#87]
Unsurprisingly, rb-fsevent doesn't work on 11.1 + M1 out of the box:

```
[2021-01-25T12:58:33.953098 #52611] ERROR -- : Exception rescued in listen-worker_thread:
Errno::EBADARCH: Bad CPU type in executable - /Users/neilconway/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rb-fsevent-0.10.4/bin/fsevent_watch
/Users/neilconway/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rb-fsevent-0.10.4/lib/rb-fsevent/fsevent.rb:140:in `popen'
/Users/neilconway/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rb-fsevent-0.10.4/lib/rb-fsevent/fsevent.rb:140:in `open_pipe'
/Users/neilconway/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rb-fsevent-0.10.4/lib/rb-fsevent/fsevent.rb:39:in `run'
/Users/neilconway/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/listen-3.4.1/lib/listen/adapter/darwin.rb:49:in `block in _run'
/Users/neilconway/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/listen-3.4.1/lib/listen/thread.rb:26:in `rescue_and_log'
/Users/neilconway/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/listen-3.4.1/lib/listen/thread.rb:18:in `block in new'
--- Thread.new ---
/Users/neilconway/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/listen-3.4.1/lib/listen/adapter/darwin.rb:49:in `_run'
/Users/neilconway/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/listen-3.4.1/lib/listen/adapter/base.rb:79:in `block in start'
/Users/neilconway/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/listen-3.4.1/lib/listen/thread.rb:26:in `rescue_and_log'
/Users/neilconway/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/listen-3.4.1/lib/listen/thread.rb:18:in `block in new'
```

**Comment by thibaudgg** [comment]
Version 0.11.0 has been released with mac M1 support, please give it a try!

**Comment by thomasdarde** [comment]
hi @thibaudgg it's unclear for me how to instruct rb-fsevent to recompile the executalble.
It still shows as intel in activity monitor

**Comment by thibaudgg** [comment]
@kevintom @PabloC I still don't have an M1 Mac to help @thomasdarde here, could you please do so?

**Comment by rylanb** [comment]
Mine is still showing as intel in activity monitor as well and I'm struggling to get 2.7.5 + rails working on my M1 MBP computer, as well.

**Comment by nate-at-gusto** [comment]
Works great on M1, this can be closed @thibaudgg
